/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class Projetar extends javax.swing.JFrame {

    float xMax;
    float sD;
    float vD;
    float qTC;
    float vB;
    float vol;
    float qTS;
    float vas;
    float sd;
    float fc;
    float aux1;
    float aux2;
    float f3;
    float Vbb;
    float fcb;
    float f3b;
    float fs;
    float db;
    float pmax;
    float qes;

    /**
     * Creates new form Projetar
     */
    public Projetar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Qts = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Qes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Vas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Fs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Sd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Xmax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Pmax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Qtc = new javax.swing.JTextField();
        VolumeIntSelado = new javax.swing.JTextField();
        FreqRessonanSelado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Calcular = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        VolumeIntGraves = new javax.swing.JTextField();
        FreqRessonanGraves = new javax.swing.JTextField();
        FreqCorteInfGraves = new javax.swing.JTextField();
        DiamDuctos = new javax.swing.JTextField();
        FreqCorteInfSelado = new javax.swing.JTextField();
        CompDuctos = new javax.swing.JTextField();
        NumDuctos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Projetar Caixa Acústica");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Parâmetros (Woofer):");

        jLabel2.setText("Fator de Mérito Total: Qts  =");

        Qts.setText("0.7");

        jLabel3.setText("Fator de Mérito Elétrico: Qes  =");

        Qes.setText("0.74");

        jLabel4.setText("Volume Equivalente: Vas  = (litros)");

        Vas.setText("9.2");

        jLabel5.setText("Frequência de ressonância: Fs  = (Hz)");

        Fs.setText("50");

        jLabel6.setText("Área Equivalente do cone: Sd  = (m²)");

        Sd.setText("0.025");

        jLabel7.setText("Deslocamento Máximo: Xmax  = (mm)");

        Xmax.setText("2");

        jLabel8.setText("Potência Máxima: Pmax  = (Wrms)");

        Pmax.setText("150");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Gabinete Selado: ");

        jLabel10.setText("Fator de Mérito Projetado: Qtc  =");

        jLabel11.setText("Volume Interno da Caixa = (litros)");

        jLabel12.setText("Frequência de Ressonância = (Hz)");

        jLabel13.setText("Frequência de Corte Inferior = (Hz)");

        Qtc.setEditable(false);
        Qtc.setPreferredSize(new java.awt.Dimension(50, 20));
        Qtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtcActionPerformed(evt);
            }
        });

        VolumeIntSelado.setEditable(false);

        FreqRessonanSelado.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Gabinete Refletor de Graves (Bass-Reflex):");

        jLabel15.setText("Volume Interno da Caixa = (litros)");

        jLabel16.setText("Frequência de Ressonância = (Hz)");

        jLabel17.setText("Frequência de Corte Inferior = (Hz)");

        jLabel18.setText("Diâmetro do(s) Ducto(s) = (polegadas)");

        jLabel19.setText("Comprimento do(s) ducto(s) = (polegadas) ");

        jLabel20.setText("Número de Ductos = ");

        Calcular.setBackground(new java.awt.Color(0, 0, 0));
        Calcular.setForeground(new java.awt.Color(255, 255, 255));
        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/solicit_accept_check_ok_theaction_6340 (1).png"))); // NOI18N
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Limpar.setBackground(new java.awt.Color(0, 0, 0));
        Limpar.setForeground(new java.awt.Color(255, 255, 255));
        Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/actions_edit_clear_15784.png"))); // NOI18N
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1495574615-map-location-solid-style-08_84567 (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/PROJETAR_Easy-Resize.com.jpg"))); // NOI18N

        VolumeIntGraves.setEditable(false);
        VolumeIntGraves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeIntGravesActionPerformed(evt);
            }
        });

        FreqRessonanGraves.setEditable(false);

        FreqCorteInfGraves.setEditable(false);

        DiamDuctos.setEditable(false);

        FreqCorteInfSelado.setEditable(false);

        CompDuctos.setEditable(false);

        NumDuctos.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Calcular)
                        .addGap(10, 10, 10)
                        .addComponent(Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(VolumeIntGraves, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(FreqRessonanGraves)
                                        .addComponent(DiamDuctos)
                                        .addComponent(FreqCorteInfGraves)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NumDuctos)
                                        .addComponent(CompDuctos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Qts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Qes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Pmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Xmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Vas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VolumeIntSelado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FreqRessonanSelado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Qtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(FreqCorteInfSelado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Qts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Qes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Vas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Fs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Sd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Xmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VolumeIntGraves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FreqRessonanGraves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FreqCorteInfGraves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(DiamDuctos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Qtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(VolumeIntSelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(FreqRessonanSelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(FreqCorteInfSelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompDuctos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(NumDuctos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Calcular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Limpar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        Qts.setText("");
        Qes.setText("");
        Vas.setText("");
        Fs.setText("");
        Sd.setText("");
        Xmax.setText("");
        Pmax.setText("");
        Qtc.setText("");
        VolumeIntSelado.setText("");
        FreqRessonanSelado.setText("");
        FreqCorteInfSelado.setText("");
        VolumeIntGraves.setText("");
        FreqRessonanGraves.setText("");
        FreqCorteInfGraves.setText("");
        DiamDuctos.setText("");
        CompDuctos.setText("");
        NumDuctos.setText("");
        
    }//GEN-LAST:event_LimparActionPerformed

    private boolean isMaiorZero(String valor) {
        float v = Float.valueOf(valor);

        if (v > 0F) {
            return true;
        }

        return false;
    }

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed

        
        xMax = Float.valueOf(Xmax.getText());
        sD = Float.parseFloat(Sd.getText());
        /*qTC = Float.parseFloat(Qtc.getText());*/
        vas = Float.parseFloat(Vas.getText());
        qTS = Float.parseFloat(Qts.getText());
        fs = Float.parseFloat(Fs.getText());
        sd = Float.parseFloat(Sd.getText());


        if (!isMaiorZero(Qts.getText())) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Qts!", WIDTH);
        }
        if (!isMaiorZero(Qes.getText())) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Qes!", WIDTH);
        }
        if (!isMaiorZero(Pmax.getText())) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Pmax!", WIDTH);
        }
        if (qTC < 0.71F && qTC > 1.5F) {

            qTC = (long) (Math.round(qTC * 100.0) / 100.0);

        }

        if (!isMaiorZero(Vas.getText())) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Vas!", WIDTH);
        }
        if (fs < 0F && fs > 20000F) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Fs!", WIDTH);
        }
        if (!isMaiorZero(Sd.getText())) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Sd!", WIDTH);
        }
        if (xMax < 0.05F) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Valor incorreto. Favor revisar o valor de Xmax!", WIDTH);
        }

        
        xMax = xMax / 1000;
        
        vD = sD * xMax;

        
        qTC = (qTS + 0.1F);
        Qtc.setText(String.valueOf(qTC));
        
        vB = vas / ((qTC / qTS) * (qTC / qTS) - 1);
        
        vol = (float) (260.88779 * sd - 2.34511);

        if (vol < 0) {
            vol = 0;
        }

        while (vB > (6 * vol)) {
            qTC = qTC + 0.1F;
            vB = vas / ((qTC / qTS) * (qTC / qTS) - 1);
        }

        /*qTC vai receber*/
        float aux = qTC * 100.0F;
        qTC = (long) (Math.round(aux) / 100.0F);

        
        fc = qTC * fs / qTS;
        aux1 = 1 / (qTC * qTC) - 2;
        aux2 = aux1 * aux1 + 4;
        aux2 = (float) Math.sqrt(aux2);
        f3 = fc * (aux1 + aux2) / 2;

        vB = Math.round(vB * 100.0F) / 100.0F;
        fc = Math.round(fc * 100.0F) / 100.0F;
        f3 = Math.round(f3 * 100.0F) / 100.0F;

        Vbb = (float) (Math.pow(qTS, 2.87) * 15 * vas);
        fcb = (float) (Math.pow(qTS, -0.9) * 0.42 * fs);
        f3b = (float) (Math.pow(qTS, -0.5) * 0.619 * fcb);
        Vbb = (float) (Math.round(Vbb * 100.0) / 100.0);
        fcb = (float) (Math.round(fcb * 100.0) / 100.0);
        f3b = (float) (Math.round(f3b * 100.0) / 100.0);

        aux1 = (float) Math.sqrt(fcb);
        aux2 = (float) (39.37 * Math.sqrt(411.25 * vD / aux1));
        db = (float) (39.37 * Math.sqrt(fcb * vD));
        if (aux2 > db) {
            db = aux2;
        }

           
        
        db = (float) (Math.round(db * 100.0) / 100.0);
        float num = 0;
        float val = 0;
        float m = 0;
        float lb;

        while (val < 1) {
            num = num + 1;
            lb = (float) (3657500 * db * db / (fcb * fcb * (Vbb / (num * 0.01639))) - 1.463 * db / 2);
            aux1 = (float) Math.sqrt(pmax * 2.7 * Math.pow(10, -8) * fs * fs * vas / (num * 28.32 * qes));
            m = (float) (13.7 * aux1 / (fcb * db * db / 4));
            aux1 = 0;
            aux2 = 0;
            if (lb > 0.6) {
                aux1 = 1;
            }
            if (m < 0.15) {
                aux2 = 1;
            }
            val = aux1 * aux2;
            if (num > 5) {
                val = 1;
                
            }
        }

        if (m > 0.15) {
            JOptionPane.showMessageDialog(Limpar, Fs, "Cuidado, pois o ducto poderá assobiar!", WIDTH);
            if (db < 1) {
                JOptionPane.showMessageDialog(Limpar, Fs, "Ducto com diâmetro muito pequeno!", WIDTH);
         }
            num = num;
            /*float m = (float) (Math.round(m*100.0)/100.0); 
            float lb = (float) (Math.round(lb*100.0)/100.0);*/
        }
        

        
        
        /*ok*/VolumeIntGraves.setText(String.valueOf(vB));
        /*ok*/FreqRessonanGraves.setText(String.valueOf(fcb));
        /*ok*/FreqCorteInfGraves.setText(String.valueOf(f3b));
        /*ok*/DiamDuctos.setText(String.valueOf(db));
        CompDuctos.setText(String.valueOf(Vbb));
        NumDuctos.setText(String.valueOf(aux1));
        Qtc.setText(String.valueOf(val));
        VolumeIntSelado.setText(String.valueOf(Vbb));
        FreqRessonanSelado.setText(String.valueOf(fs));
        FreqCorteInfSelado.setText(String.valueOf(aux));
        
        /*public void inserirNoBanco(float )
{
	Connection conn = Conecao.getConexao(); // Uma instancia de MINHA classe de   Conexão
               String sql = "INSERT INTO produto(para,nomeproduto,peso,preco,descricao,quantidade) VALUES (?,?,?,?,?,?)";// UTILIZEI SEUS CAMPOS QUE PEGUEI NO
                                                                                                                                                                                  // CÓDIGO
              PreparedStatement stmt = conn.PreparedStatement(sql); // AQUI ESTÁ O USO DO PreparedStatement
              stmt.setInt(1,cod);                 
              stmt.setString(2,nomeProdudo);        
              stmt.seDouble(3,peso);                 //NESSA PARTE DO CÓDIGO, SETA-SE AS VARIÁVEIS QUE PASSA POR PAREMETRO NO 
              stmt.setDouble(4,preco);                 //MÉTODO PARA O STMT QUE É DO TIPO PreparedStatement
              stmt.setString(5,descricao);                                         
              stmt.setInt(6,quantidade);
              stmt.execute(); // Executa o PreparedStatement com o SQL já incluso e os valoes Setados
             stmt.close(); // Fecha o PreparedStatement após a execução
}
       /* Statement
                resultset
                connection*/
    }//GEN-LAST:event_CalcularActionPerformed

    private void QtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaPrincipal p = new TelaPrincipal(); //instancia da tela principal
        p.show(); //abre a tela principal
        this.dispose(); //fecha a tela de login
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VolumeIntGravesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeIntGravesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeIntGravesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projetar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projetar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projetar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projetar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projetar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField CompDuctos;
    private javax.swing.JTextField DiamDuctos;
    private javax.swing.JTextField FreqCorteInfGraves;
    private javax.swing.JTextField FreqCorteInfSelado;
    private javax.swing.JTextField FreqRessonanGraves;
    private javax.swing.JTextField FreqRessonanSelado;
    private javax.swing.JTextField Fs;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField NumDuctos;
    private javax.swing.JTextField Pmax;
    private javax.swing.JTextField Qes;
    private javax.swing.JTextField Qtc;
    private javax.swing.JTextField Qts;
    private javax.swing.JTextField Sd;
    private javax.swing.JTextField Vas;
    private javax.swing.JTextField VolumeIntGraves;
    private javax.swing.JTextField VolumeIntSelado;
    private javax.swing.JTextField Xmax;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
